### ISSUE TITLE
Different NameServer than Route53

### ISSUE THREAD

**Issue by lucmichalski** [Samsung-AG/kraken#147]
Hey guys,

Kraken is really good ^^, but how can I use a different DNS than Route 53 for deploying Kraken ?

Also, is the Kube-UI addon from Kraken using the graph extension ?
https://github.com/kubernetes-ui/graph

Thanks for any reply or additional doc about the questions above.

Cheers,
Luc Michalski

**Comment by maratoid** [comment]
Hello!

Which DNS provider did you have in mind? 

Also - no, we are not using the graph extension on KubeUI - but you could always deploy your own service onto the cluster.

**Comment by lucmichalski** [comment]
Thanks for your reply !

I am using dnsmadeeasy for one domain and using ec2 instances on aws. Some legacy prevents me to migrate to ROUTE53 for the moment.

**Comment by maratoid** [comment]
So it looks like terraform actually supports DNSMadeEasy as a provider:

https://terraform.io/docs/providers/dme/index.html

You could do some hacking on the 'aws_route53_record' sections of [aws.tf](https://github.com/Samsung-AG/kraken/blob/master/terraform/aws/aws.tf) 

```
resource "aws_route53_record" "master_record" {
  zone_id = "${var.aws_zone_id}"
  name = "${var.aws_user_prefix}-master.${var.aws_cluster_domain}"
  type = "A"
  ttl = "30"
  records = ["${aws_instance.kubernetes_master.public_ip}"]
}
resource "aws_route53_record" "proxy_record" {
  zone_id = "${var.aws_zone_id}"
  name = "${var.aws_user_prefix}-proxy.${var.aws_cluster_domain}"
  type = "A"
  ttl = "30"
  records = ["${aws_instance.kubernetes_node_special.0.public_ip}"]
}
```
and replace them with appropriate 'dme_record' s for dnsmadeeasy.

Pull requests are always welcome.

**Comment by maratoid** [comment]
Let me know if this answers your question.

**Comment by lucmichalski** [comment]
I purchased another domain as i just wanted to do other tests. But thanks for the insight !
