### ISSUE TITLE
Custom Services/Addons/Security

### ISSUE THREAD

**Issue by lucmichalski** [Samsung-AG/kraken#153]
Hi,

Just wanted to know, if you have some insights about these points and kraken:

- How to configure and use a private docker registry (.docker.cfg for quay.io or any private registries) to deploy additional services from a private github repo (Along of the Kraken Service repo):
   - Vulcand Proxy:
     - https://quay.io/repository/rainbean/vulcand (Main reverse proxy for the Kubernetes Cluster)
     - https://quay.io/repository/timeline_labs/romulusd (Discover new kube webservices and register them into vulcand)
   - Traefik (Alternative Reverse Proxy that seems promising):
     - https://github.com/EmileVauge/traefik
   - ElasticSearch Cluster:
     - https://github.com/pires/kubernetes-elasticsearch-cluster
   - Kubernetes ELK:
     - https://github.com/pires/kubernetes-elk-cluster

- How it would be possible to increase the security and grouping monitoring UIs together:
     - Not exposing public IPs of nodes
     - Keep up to date AMIs
     - Setup TLS
     - Individual node can reboot and the cluster will still function
     - Internal cluster DNS is available
     - Service accounts enabled (https://github.com/coreos/coreos-kubernetes)
     - Like for ELK, having a .htpasswd in order to secure the kube system UIs (graphana,kube-ui,etc,kibana)
     - Automate the registration of Cluster-Monitoring/Grafana to the Kube System public endpoints
     - Import a verified SSL certificate for the cluster domain

Thanks in advance for your input on those

Cheers,
Luc Michalski

**Comment by spiffxp** [comment]
> How to configure and use a private docker registry (.docker.cfg for quay.io or any private registrieso)

Set the `dockercfg_base64` variable in your terraform.tfvars file with the base64-encoded contents of a `.docker.cfg` of your choice, eg:
```sh
$ cat ~/.dockercfg | base64
```

> deploy additional services from a private github repo

We would need to add the ability to deploy from multiple repos.  In the meantime, you could fork the kraken-services repo, and add these services into your fork either via copy-paste if their respective licenses allow for it, or git submodules/subtrees.  You can then specify a different services repo to use via the `kraken_services_repo`  variable.

We would need to add the ability to deploy services from private repos.  This would probably involve changes at the ansible vs. terraform level, and look something like dropping a private ssh key / deploy key onto the hosts.

PR's welcome

**Comment by spiffxp** [comment]
> Not exposing public IPs of nodes

Can you explain what you mean here?  Nodes have public IP's automatically assigned, but they are registered under kubernetes with their private IP's.  To my knowledge the only public IP's the system knows about are exposed via the route53 records we setup.

> Keep up to date AMI's

We lean on coreos' AMI's for this purpose, and do not maintain AMI's of our own.

> Internal cluster DNS is available

This is available today, provided by the skydns service in kraken-services.

> Setup TLS
> Service accounts enabled
> Import a verified SSL certificate for the cluster domain

I believe the plumbing for this is in place already, though it could probably be fleshed out a bit more.  Certs are generated by scripts in the [generate-cert](https://github.com/Samsung-AG/kraken/tree/master/generate-cert) directory, and the appropriate parameters and TLS are plumbed through to ansible, eg: https://github.com/Samsung-AG/kraken/blob/master/ansible/roles/kubernetes/defaults/main.yaml#L26-L28

> Individual node can reboot and the cluster will still function

At this time, kubernetes doesn't support multiple schedulers or controller-managers.  We would need to modify kraken to standup a hot/cold standby pattern for these components.

Using apiserver pooling will allow the cluster to continue to function if an apiserver dies.  If all apiservers die, the nodes will continue to operate under their last known configuration; pods that were running will remain running.

Kubernetes will automatically reschedule pods if a node dies.

> Like for ELK, having a .htpasswd in order to secure the kube system UIs (graphana,kube-ui,etc,kibana)
> Automate the registration of Cluster-Monitoring/Grafana to the Kube System public endpoints

Unclear what you mean here.  I believe [kubernetes' api server proxying](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/accessing-the-cluster.md#discovering-builtin-services) allows you to front services behind whatever authn/authz model you have setup for the kubernetes api.  The `kubectl cluster-info` command [defaults to a namespace and uses a label selector](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/clusterinfo.go#L66-L70) so you could either tell it to look in an alternate namespace, or modify your service definitions appropriately
