### ISSUE TITLE
Hypernetes/Kubernetes

### ISSUE THREAD

**Issue by lucmichalski** [Samsung-AG/kraken#192]
Hi guys,

Hope you are all well !

I was wondering if you have seen this repo: https://github.com/hyperhq/hypernetes

From their description:
Hypernetes is a secure, multi-tenant Kubernetes distro. Simply put,
Hypernetes = Bare-metal + Hyper + Kubernetes + KeyStone + Cinder + Neutron.

Do you think that would fit in the kraken repo roadmap ?

Ps. Your work is really amazing guys ! :-)

Cheers,
Luc

**Comment by maratoid** [comment]
Hello again!

We're definitely interested in the bare-metal part. Haven't seen this before - thanks for the link.
