### ISSUE TITLE
How do you push ansible updates?

### ISSUE THREAD

**Issue by manojlds** [Samsung-AG/kraken#193]
This project has been a good guidance for me. I am new to Terraform/CoreOS/Kubernetes.

One thing I am trying to figure out - how do you push updates to your ansible roles?

**Comment by maratoid** [comment]
If you are talking about updating the cluster with ansible after initial creation you can do it with:

    ansible-playbook --inventory-file terraform/<cluster type>/rendered/ansible.inventory ansible/iaas_provision_local.yaml

**Comment by manojlds** [comment]
@maratoid - ah got it, thanks for the pointer!
