### ISSUE TITLE
Issues running kubectl exec

### ISSUE THREAD

**Issue by manojlds** [Samsung-AG/kraken#195]
I am getting `error: unexpected response status code 400 (Bad Request)` when running something like `kubectl exec busybox -- ls`

Some digging seems to point that putting nginx infront of the apiservers is not really supported, and could be the reason.

I want to confirm that this is an issue with your cluster? (I am using this as reference, but not as is)

**Comment by spiffxp** [comment]
Can confirm this is an issue with our setup.  The issue is with our nginx fronting the cluster at the moment.  We're working to add HTTP2/SPDY support, which will enable `kubectl exec` and a few other commands.

**Comment by manojlds** [comment]
Great, thanks for the quick response! Should this issue be kept open?

**Comment by spiffxp** [comment]
Yes, we'll close once we've confirmed `kubectl exec` works

**Comment by maratoid** [comment]
Fixed in https://github.com/Samsung-AG/kraken/pull/226
